application: hyades-a
version: secureable
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: /favicon\.ico
  static_files: static/favicon.ico
  upload: static/favicon\.ico
  secure: optional

- url: /static/base(\.[0-9])\.css
  static_files: static/base.css
  upload: static/base\.css
  secure: optional

- url: /static
  static_dir: static
  secure: optional

- url: /admin
  login: admin
  script: mirror.py
  secure: optional

- url: /cleanup
  login: admin
  script: mirror.py
  secure: optional

- url: /kaboom
  login: admin
  script: mirror.py
  secure: optional

- url: /.*
  script: mirror.py
  secure: optional
